### ISSUE TITLE
Deprecated rollup.json config options

### ISSUE THREAD

**Issue by dom-nie** [FraxFinance/fraxtal-node#3]
While upgrading a node and fetching a new rollup.json, I encountered the following errors. These were deprecated in the op-node with the commit: https://github.com/ethereum-optimism/optimism/commit/cceb207a166d7b190f7731e28300b8113fb1987b.

`docker logs -f mainnet-mainnet-node-1
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20240226-r0)
(2/7) Installing brotli-libs (1.0.9-r14)
(3/7) Installing libunistring (1.1-r1)
(4/7) Installing libidn2 (2.3.4-r1)
(5/7) Installing nghttp2-libs (1.57.0-r0)
(6/7) Installing libcurl (8.9.1-r1)
(7/7) Installing curl (8.9.1-r1)
Executing busybox-1.36.1-r7.trigger
Executing ca-certificates-20240226-r0.trigger
OK: 12 MiB in 22 packages
t=2024-10-18T10:16:36+0000 lvl=crit msg="Application failed" message="failed to setup: unable to create the rollup node config: failed to decode rollup config: json: unknown field \"basefeeScalar\""`

`docker logs -f mainnet-mainnet-node-1
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20240226-r0)
(2/7) Installing brotli-libs (1.0.9-r14)
(3/7) Installing libunistring (1.1-r1)
(4/7) Installing libidn2 (2.3.4-r1)
(5/7) Installing nghttp2-libs (1.57.0-r0)
(6/7) Installing libcurl (8.9.1-r1)
(7/7) Installing curl (8.9.1-r1)
Executing busybox-1.36.1-r7.trigger
Executing ca-certificates-20240226-r0.trigger
OK: 12 MiB in 22 packages
t=2024-10-18T10:16:36+0000 lvl=crit msg="Application failed" message="failed to setup: unable to create the rollup node config: failed to decode rollup config: json: unknown field \"blobBasefeeScalar\""`

**Comment by 0xalex88** [comment]
Closed by #4
